name: actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  # run manually
  workflow_dispatch:
  # run on push
  push:
    branches:
    - main
jobs:
  Explore-GitHub-Actions:
    permissions: 
        contents: write
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: stanislas1200
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
